-- 002_seed.sql
-- Seed data for development

-- Admin account: nickname=admin, password=Admin@12345 (bcrypt hash generated by app or manually)
-- For initial bootstrap you can create admin in app or run SQL with a real hash.
-- Here we insert invite codes and sample matches only.

-- Invite codes
insert into public.invite_codes (code, is_active)
values
  ('WORLD2026', true),
  ('FRIENDS26', true),
  ('GOAL2026', true)
on conflict (code) do nothing;

-- Sample matches
with m1 as (
  insert into public.matches (league, stage, home_team, away_team, start_time, status)
  values ('世界杯', '小组赛 A 组', 'A1', 'A2', now() + interval '3 days', 'scheduled')
  returning id
),
m2 as (
  insert into public.matches (league, stage, home_team, away_team, start_time, status)
  values ('世界杯', '小组赛 A 组', 'A3', 'A4', now() + interval '3 days 2 hours', 'scheduled')
  returning id
),
m3 as (
  insert into public.matches (league, stage, home_team, away_team, start_time, status)
  values ('世界杯', '小组赛 B 组', 'B1', 'B2', now() + interval '4 days', 'scheduled')
  returning id
),
all_m as (
  select id from m1 union all select id from m2 union all select id from m3
)
insert into public.markets (match_id, market_type, title, options, multiplier)
select
  m.id,
  v.market_type::public.market_type,
  v.title,
  v.options::jsonb,
  v.multiplier::numeric
from all_m m
cross join (
  values
    ('1x2', '胜平负', '["home","draw","away"]'::jsonb, 1.80),
    ('exact_score', '准确比分', '["0-0","1-0","0-1","1-1","2-0","0-2","2-1","1-2","2-2","3-0","0-3","3-1","1-3","3-2","2-3","other"]'::jsonb, 7.00),
    ('total_goals', '总进球', '["over2.5","under2.5"]'::jsonb, 1.90),
    ('btts', '双方是否进球', '["yes","no"]'::jsonb, 1.85),
    ('ht_1x2', '半场胜平负', '["home","draw","away"]'::jsonb, 2.20)
) v(title, market_type, options, multiplier);
